### ISSUE TITLE
Be able to choose the difficulty

### ISSUE THREAD

**Issue by Nico207** [tube42/9P#10]
It would be interesting to unlock each new level according to a certain number of points. This would make possible to set up levels of difficulty.

For example: 

- in **easy** mode, the next level will be unlocked if the player find at least one 6 letters word and get 50 pts (1 point per letter of the words found -> 4 letters word=4pts, 5 letters word=5pts...)
- in **normal**, the next level will be unlocked if the player finds at least one 7-letter word and gets 65 points
- in **hard**, the next level will be unlocked if the player finds at least one 8-letter word and gets 80 points
- in **insane**, the next level will be unlocked if the player finds all 9 letters words and gets at least 100 points

**Comment by tube42** [comment]
Hmm...  I don't know if people would try very hard if they could play on Easy.

But lets finish the French version and then we can get back and look into new features.

**Comment by Nico207** [comment]
I may not propose the right solution, but it was to say that it would be good if the game were accessible to many people as possible.

**Comment by tube42** [comment]
Maybe a better solution is to have increasing difficulty. So the first 9 are easy, the second 9 are a bit harder and so on.

This would allow people to get into the game but only the really good players would get very far.

**Comment by tube42** [comment]
Having thought a bit more on this, I think having an "easy" level would just suck the fun out of this game.

I will change the hardness a bit, but it will probably go the other way and make it harder and more strict.
