### ISSUE TITLE
Score suggestion 

### ISSUE THREAD

**Issue by miguelosmondo** [tube42/9P#13]
My daughter and I enjoy this game immensely. Currently the game board shows nothing of the player's progress (you have to press the left arrow button.) We suggest a score that updates after every successful word, displayed somewhere on the game board screen. A 4 letter word could be worth 4 points, a 5 letter word 5 points, etc.

Also any kind of sound effects you could add would make the game feel more interactive.

**Comment by tube42** [comment]
I need  to figure out where I can put the score otherwise it sounds like a great idea.

**Comment by tube42** [comment]
Score and sound was added in v0.1.0.

It should hit f-droid servers in 1-2 weeks.

**Comment by miguelosmondo** [comment]
Excellent! Thank you! 

On January 4, 2019 2:21:16 PM CST, "Tubeman, The" <notifications@github.com> wrote:
>Score and sound was added in v0.1.0.
>
>It should hit f-droid servers in 1-2 weeks.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tube42/9P/issues/13#issuecomment-451557616


"Where there is love there is life."
Mahatma Gandhi
