### ISSUE TITLE
Levels beyond 81 are inaccessible

### ISSUE THREAD

**Issue by SadisticMystic** [tube42/9P#15]
The Android level data file indicates that there are supposed to be 144 levels. However, the two-step 3x3 selection grid shows only "1-9", "10-18", and so on to "73-81". Even after finding a three-star word in all 81 levels, there's no apparent interface for scrolling to a new set of levels so that the boxes for 82-90 can appear. Was such a thing ever meant to be implemented yet?

**Comment by tube42** [comment]
The idea was to have no more than 9x9 levels, but the program that generates these level is limited to 100 (or 144 in case of the English levels).

I don't know how many people will ever get to level 81. If too many do, I might add more levels.

Close this issue if you are satisfied with this answer.
