### ISSUE TITLE
Slowdown after extensive play session

### ISSUE THREAD

**Issue by florentc** [tube42/9P#3]
Version: 0.0.7
LineageOS 14.1

When playing a level for an extended amount of time, the framerate eventually drops down. The menus are always fine but the animations in a given level only recover smoothness after restarting the application (going back to the menu and then back to the level does not do the trick).

**Comment by tube42** [comment]
This is odd. Could you provide some additional information to track this down?

1. How long is "extended amount of time", are we talking hours?
2. Do you have a stack trace or any other log messages?
3. Can you check how much memory the game uses during play time?
4. I understand this only happens in the game screen. If you go to the main menu and change to another level will the issue disappear?

Thanks for reporting this.

**Comment by tube42** [comment]
A new version is out that I hope fixes this issue - #v0.0.8.
It may take up to a week for fdroid to update their copy, but I would appreciate if you could test it and report back to me in this thread.

**Comment by florentc** [comment]
It seems the issue is fixed in v0.0.8. Thank you.

**Comment by tube42** [comment]
great, thanks for reporting the issue.
