### ISSUE TITLE
Adding multilanguage

### ISSUE THREAD

**Issue by Nico207** [tube42/9P#6]
Hi,

I have added french words in the wordlists repository :
[https://gitlab.com/tube42/wordlists/merge_requests/1](https://gitlab.com/tube42/wordlists/merge_requests/1)

Can you add them into P9 with the possibility of selecting the language ?

Thanks !

**Comment by tube42** [comment]
I am not confident I can add any other languages to P9, but lets start with getting the word list in place and see what we can go from there.

**Comment by tube42** [comment]
There is a French branch with initial French support here:

https://github.com/tube42/9P/tree/french

Can you help me test it?

**Comment by Nico207** [comment]
I am ready to help but, is it possible to have an apk file to download?

**Comment by tube42** [comment]
Sure, try this:

https://github.com/tube42/tube42.github.io/raw/master/9p/android-debug.apk

You may need to uninstall the fdroid version first since these are not signed with the same key.

**Comment by Nico207** [comment]
This new version is on the good way.  On my side, I should perhaps review the integration of some words (especially the names of cities)

**Comment by tube42** [comment]
Ah, should not have closed this one yet.

Can you help me translate some in-game text too? like menus and stuff.

**Comment by Nico207** [comment]
Here are the strings I found and their translations:

```
"about" : "À propos"
"settings" : "Paramètres"
"play" : "Jouer"
"a word puzzle i made since i love word puzzles..." : "Un puzzle de mots que j'ai fait car j'adore les puzzles de mots...."
"the objective is to find the 9-letter word and unlock more levels." : "L'objectif est de trouver le mot de 9 lettres et de débloquer plus de niveaux."
"once you have unlocked them all, well congrats, you now know many unusual words..." : "Une fois que vous les avez tous déverrouillés, eh bien félicitations, vous connaissez maintenant beaucoup de mots inhabituels..."
"level" : "Niveau"
"sound on" : "Son allumé"
"sound off" : "Son éteint"
"fun off" : "Amusant"
"boring on" : "Ennuyeux"
"delete progress" : "Supprimer la progression"
"confirm" : "Confirmer"
"deleted" : "Progression supprimée"
```
A quick question : What is the purpose of the "funoff" parameter?

**Comment by tube42** [comment]
This is current result:

![img001](https://user-images.githubusercontent.com/1971317/48033429-8ede3180-e15b-11e8-9426-b0eda6b003b1.png)
![img002](https://user-images.githubusercontent.com/1971317/48033432-91408b80-e15b-11e8-8436-9969bae3307b.png)
![img003](https://user-images.githubusercontent.com/1971317/48033433-930a4f00-e15b-11e8-8ad0-420c53a417c3.png)
![img004](https://user-images.githubusercontent.com/1971317/48033437-94d41280-e15b-11e8-8665-fae65fbcbdb4.png)
![img005](https://user-images.githubusercontent.com/1971317/48033442-96053f80-e15b-11e8-9de1-c646a153ee71.png)

I am not very familiar with the French alphabet. Are "é è á à ç" all French letters I will need?

**Comment by Nico207** [comment]
Everything seems almost perfect.
Can you change just two little things : on the third screenshot, the end of the first sentence must terminate with three point; and bettwen "niveau" and "Une" there must be one point followed by one space ("niveau. Une").

About French letters, there are many other letters used:
```
Uppercase : É È Ç À Æ Â Ê Ÿ Û Î Œ Ô Ä Ë Ü Ï Ö Ù
Lowercase : é è ç à æ â ê ÿ û î œ ô ä ë ü ï ö ù
```

**Comment by tube42** [comment]
Still a bit too big but lets go with that for now.

The new version will show up in fdroid in a week or so, you might need to uninstall the beta version to install that.

Closing this now, thanks for your help!
