### ISSUE TITLE
Game not saved

### ISSUE THREAD

**Issue by Nico207** [tube42/9P#7]
After selected french (or english) and find some words, I leave the game. When I returned, all the words found were lost.

**Comment by tube42** [comment]
Is this issue present only in the new version with French support?

**Comment by Nico207** [comment]
Yes, only in the multilanguage version.

**Comment by tube42** [comment]
I cannot re-create this on PC or Android. Try exiting the app with back button and see if it changes anything.

**Comment by Nico207** [comment]
After remove the basic version, and reinstallation of the multilingual version, it seems to work again...

I will redo an installation, taking care to delete the old data.
I would also try to install it on another phone to see if I have the same problem.

**Comment by Nico207** [comment]
Well... I can't reproduce this bug anymore...
Sorry for the inconvenience.
