### ISSUE TITLE
Unable to unlock levels

### ISSUE THREAD

**Issue by Nico207** [tube42/9P#8]
Even if I find the longest word in one of the 3 first unlocked level, no next level is unlock.

**Comment by tube42** [comment]
I tried this on PC and it worked fine. Let me repeat this on Android an come back to you.

**Comment by Nico207** [comment]
I tried it on the F-Droid version (v0.0.8) with the same result. On the first level, I found all the words with a length of 9 letters and lots of words with a length of 8 letters, but no other has been unlocked.

What is the trigger to unlock a level?

**Comment by tube42** [comment]
You need find one 9-level word in the first three level to unlock the rest. 

Check if it works.

**Comment by Nico207** [comment]
Sorry, it doesn't work...

**Comment by tube42** [comment]
Hm, lets dig deeper...

When you find a 9 letter word, three things will happen
1. you see the 3-star filled on the top of the game screen for a few seconds
2. when you leave the game page, your stats have been updated on the next page 
3. when you leave that page you are back on the level selection page and even there you can see the three stars filled.

Can you see any of these happening?

**Comment by Nico207** [comment]
Yes, 
I see the 3 stars on the top of the screen when I complete the longest word, 
on return, the stats is correctly updated
on the level selection, I see the 3 stars on the level where I found the word.

<img alt="screenshot_20181020-170327" src="https://user-images.githubusercontent.com/1179972/47257152-8a8ef480-d48a-11e8-80be-0de6eae6bbcf.png" width="200"> <img alt="screenshot_20181020-170336" src="https://user-images.githubusercontent.com/1179972/47257153-8e227b80-d48a-11e8-8833-0ce9a5e5717a.png" width="200"> <img alt="screenshot_20181020-170340" src="https://user-images.githubusercontent.com/1179972/47257154-8fec3f00-d48a-11e8-88bf-71150deb85fb.png" width="200">

**Comment by Nico207** [comment]
Okay, I understood my mistake...  :scream:
I understood that I had to find the longest word in ONE level to unlock another. But I must find the longest word in the 3 levels to be able to continue.
After doing this, the other 6 levels unlocked.
Sorry for this problem which finally concerned my level in English  :no_mouth:
